### PR TITLE
Add hidden and draft archives

### PR DESCRIPTION
**Pull request by pfrazee**
Two additions:

 - All dat archives now have a `hidden` user setting which, if true, will hide the archive from listings (in the library or in the select archive modal). Only available to Beaker's internal software. Useful for internal archives.
 - Adds a "draft" archive concept which enables a "master" archive to have multiple "draft" archives (which should be hidden). Drafts can be added to (`beaker.archives.addDraft()`), removed (`beaker.archives.removeDraft()`), and listed (`beaker.archives.listDrafts()`). Can also set an "active draft" (`beaker.archives.setActiveDraft()`) which controls which of the draft-set is actively synced to the `localSyncPath` if one is set. Calling `setActiveDraft()` will replace the content of the `localSyncPath` with the data of the draft dat, similar to a Git checkout.

API:

```
beaker.archives.listDrafts (masterUrl)
beaker.archives.setActiveDraft (masterUrl, draftUrl)
beaker.archives.addDraft (masterUrl, draftUrl)
beaker.archives.removeDraft (masterUrl, draftUrl)
```

You can call `setActiveDraft` with `masterUrl == draftUrl` to set the master to the active draft.

### CODE REVIEW

**Comment by pfrazee** [comment]
Tests are in the beaker repo

**Comment by pfrazee** [comment]
Published `1.2.0`

**Comment by taravancil** [comment]
Notes from conversation with @pfrazee. A few updates required:

- [ ] Set local sync path should safely handle non-active drafts
- [ ] `addDraft` should fail when called with draft as first parameter
- [ ] Need an easy way to get draft info with a draft URL, for when library view is opened on a draft

**Comment by pfrazee** [comment]
Updates published `1.3.0`

**Pull request merged**
